ipfs-shipyard/peer-pad

src/components/Codemirror.css
src/components/Editor.js

Configures markdown mode and styles syntax

---

README.md

View the change here: https://github.com/ipfs-shipyard/peerpad/blob/22b8c3a95b900425c4ce2db88b7630c184c8d98b/README.md

Adds logo to readme and changes capitalisation of PeerPad

---

src/components/CreateDocument.js
src/components/Home.js
src/components/__snapshots__/Home.test.js.snap
src/index.css

| sm | md | lg  |
|----|----|----|
| <img width="361" alt="screenshot 2017-10-23 11 03 50" src="https://user-images.githubusercontent.com/58871/31883668-8563f4ee-b7e2-11e7-9571-81bb77087e07.png"> | <img width="753" alt="screenshot 2017-10-23 11 03 28" src="https://user-images.githubusercontent.com/58871/31883679-8eede768-b7e2-11e7-929d-a4e94afca32b.png"> | <img width="1355" alt="screenshot 2017-10-23 11 16 20" src="https://user-images.githubusercontent.com/58871/31884002-a2f9d982-b7e3-11e7-9b06-fcdbac138a03.png"> |

Adds responsive homepage footer

---

src/components/Codemirror.css
src/components/Edit.js
src/components/Editor.js
src/components/Status.js
src/components/header/buttons/NewButton.js
src/components/header/buttons/NotificationsButton.js
src/components/toolbar/Toolbar.js
src/components/toolbar/buttons/Button.js
src/index.css

Fix #55 - Disable non-implemented UI features
Fix #57 - move IPFS node status up to header and make writing area bigger

Disabled missing features, move network status

---

package.json
src/components/home/Hexicon.js
src/components/home/Home.css
src/components/home/Home.js
src/components/home/__snapshots__/Home.test.js.snap
src/components/toolbar/buttons/LinkButton.js

Quick fix to get app working, when mounted on a path other than the domain root.
WIP on #67 
With these changes in I can load the app when it's deployed to ipfs, but I can't get peers to sync atm.
The prod build version of this commit is on ipfs at
https://ipfs.io/ipfs/QmYD5hksXbSRRY4C3fFsneBuCqfcU8JS64wfLum896jFBc
Some of the changes in this PR workarounds to placate webpack, so meh. Specifically I had to pull a relative url up out of css to the html as the css loader failed when the image wasn't located next to the css.

Relative all the URLs

---

config/webpack.config.prod.js

disabled uglification on the production build

---

docs/ARCHITECTURE.md

"Saving" and "publishing" can be confusing while we're not pinning anything anywhere yet.

Be more cautious with wording around saving / persistence

---

package.json
src/components/Edit.js
src/components/header/buttons/NewButton.js
src/components/header/buttons/NotificationsButton.js
src/components/header/buttons/PeersButton.js
src/components/toolbar/Toolbar.js

feature: peer aliases

---

src/components/home/Home.css
src/components/home/Home.js
src/components/home/__snapshots__/Home.test.js.snap
src/index.css

This PR will:
- Polish navigation hover states (smoother transitions, better hover state for main logo)
- Clean up the footer
Hover states for the nav links:
Logo in upper left of header now has a dim only and no underline. I also smoothed out the dim animation a wee bit.
Adjusted the footer so the links don't wrap as often and to give some visual balance:
I think the header could still use some responsive love, but I plan to address that in another pass.
Would love any thoughts you have on this! Thanks!
cc @diasdavid @akrych @one000mph

Homepage - Improve header and footer navs

---

.gitignore
package-lock.json
package.json
src/components/home/__snapshots__/Home.test.js.snap

- Update peerpad-core to v0.11
- Add package-lock https://github.com/ipfs-shipyard/peer-pad/issues/150#issuecomment-385643974
- Update jest snapshots to fix Home.test.js

(chore): Update and pin deps

---

package-lock.json
package.json

This should bring more speed and stability (addressing #165).

chore: update peer-pad-core dep to v0.12.0

---

Makefile
config/env.js
config/webpack.config.prod.js
package-lock.json
package.json
src/index.js

chore: make rollbar use source-maps for errors

---

config/webpack.config.prod.js
package.json

chore: final fixes for getting sourcemap support (#232)

---

src/components/home/Home.js

Also change name of github project from 'peerpad' to 'peer-pad'.

Remove "Architecture" link which is broken.

---

src/components/Edit.js

This commits add a simple status indicator that currently shows the
following states:
- Saving - State change happened locally
- Receiving - State change happened externally
- Timeout - After receiving a state change from ourself, this happens
after SAVE_TIMEOUT_MS, occurs if the pinner doesn't pin quick enough
- Saved - Pinner acknowledged it pinned the current state
However, this commit has a issue where sometimes the `stage change`
event happens multiple times in a row, and the `pinned` event happens in
the middle of those, but not in the end, leading to the `Receiving`
state to be shown until another event happens. Currently trying to
reproduce this directly in `peer-star-app`
See example of bug happening in peerpad here: https://ipfs.io/ipfs/QmUBh45vMG1axbhKdfYqcZqFBU3CM1eVwm6SBdRUPNF …

Feature: show saved status in pads

---

src/components/Edit.js

This also removes a small about of duplication.

Reenable editor after hiding and showing

---

src/rollbar.js

fix: activate rollbar for dev.peerpad.net as well

---

package-lock.json
package.json
src/components/Edit.js
src/components/home/Home.js
test/e2e-load/spawn-cluster.js

Also, upgrades to latest peer-base v0.11.0.

Chore: peer-star-app => peer-base

---

package-lock.json
package.json
test/e2e-load/index.js
test/e2e-load/read-only-replica.js
test/e2e-load/replica-add-text-behavior.js
test/e2e-load/replica-change-text-behavior.js
test/e2e-load/spawn-cluster.js

New release candidate for peer-base.
Also, runs E2E load tests with 8 different replicas.

chore: upgrades to peer-base v0.12-rc3 and hardens e2e load tests

---

src/components/Doc.js
src/components/Edit.js
src/components/header/Header.js
src/components/toolbar/Toolbar.js

Quick fixes for the next round of testing.

UI Tweaks ... use full width, scroll in wide code blocks, hide debugging

---

.gitignore
config/env.js
src/components/Edit.js
src/config.js

This will make development easier for me.

Use WEBSOCKET_STAR and APP_NAME settings from .env

---

src/components/Edit.js
src/config.js

Reverts ipfs-shipyard/peer-pad#321
Actually, I need a solution for the static builds ... revert this.

Revert "Add APP_NAME_(DEV|PROD) and WEBSOCKET_STAR_(DEV|PROD)"

---

src/config.js

Hopefully this will use the correct one for production deploy.

Different approach for default swarm address

---

src/components/Edit.js

Add default app name for production
