ipfs-shipyard/peer-pad

src/components/Edit.js
src/components/SnapshotLink.js
src/components/toolbar/buttons/SnapshotsButton.js

- Tweak snapshot ui to show timestamp and give enough space to see full hash, and use a monospace font to make the length predictable.
- Store and load snapshots from localStorage to persist them across sessions.
- Prefetch snapshots from gateway to speed up first render.
- Add local `createdAt` time property to snapshots. (ISO 8601 string)
- Adds `title` property which is now the mutable doc title. `name` is immutable and part of the url.  See: #62 
Fixes #56 
Fixes #54

Store snapshots in localStorage and prefetch from gateway

---

package.json
src/components/Edit.js

- Check if local node is already started
- Upgrade to peerpad-core@0.6.0
- Show status as "online" in ui
Fix #58

Check if local node is already started

---

package.json
src/colors.css
src/components/Doc.css
src/components/Doc.js
src/components/DocViewer.js
src/components/DocViewerHTML.js
src/components/Preview.css
src/components/Preview.js

Adds `Doc` component and css to share as much of the document preview styling as is sensible between the in editor preview and a published snapshot of a document.
Adds some eyeball soothing default styles for rendered markdown features and generally improves the look and feel of our docs. 💅 
As time allows I'd like to isolate the preview document styles from the rest of the editor using [css-modules](https://github.com/css-modules/css-modules) or similar, but that is a PR for later.
Fixes #51 
---

Styles for published snapshots

---

package.json
src/components/DocViewer.js
src/components/Editor.js
src/components/EditorArea.js
src/components/Preview.js
src/components/home/CreateDocument.js
src/components/home/__snapshots__/Home.test.js.snap
src/components/toolbar/Toolbar.js
src/components/toolbar/buttons/LinkButton.js

Equation lovers, this PR is for you!
- I have added a new type of pad called `Math pad`. This supports basic latex via `KaTex`!
- There is now support for `$E = mc^2$` (inline) and `$$y=f(x)$$` (block).
- It works in preview as well!
This PR will only work if the PR on https://github.com/ipfs-shipyard/peerpad-core/pull/2
Related links:
- [Pad with some examples](https://gateway.ipfs.io/ipfs/QmbgcTxNdVnFk4wsvxnovugRXBX8NsiqNBoiv1nVUJhLva/index.html#/w/math/SP8B6HwHQFRpknFbTSxBvA/4XTTM6TKdN4C8g4j7bcoh1M8tQdVbmbr9HFcJ6hhE85MEFTrj/K3TgUEgELeNmzdWrsvRpPbsQuUKzEAwGcHmeFckE2B6yyrsWsJ18aZkrffdgNcqzngqm6GKEbwWzp9uh5WPRi59bhMsv8feYeeK6txSvKxtKkCeTDSZLrQ62b3YdjdDKJpsz46y1)
- [Peerpad with the PR](https://gateway.ipfs.io/ipfs/QmbgcTxNdVnFk4wsvxnovugRXBX8NsiqNBoiv1nVUJhLva/index.html)!
---
Note: this …

Adding a new type of pad: Math!

---

docs/ARCHITECTURE.md

I removed a warning that said that encrypted local storage
was not yet implemented because the issue it linked to (#4)
has since been closed.

docs: Remove outdated warning in ARCHITECTURE

---

test/e2e/smoke.test.js

- Test error if any request results in a >=400 status code.
- Use waitFor to wait for the doc titles to match rather than waiting for 5s

(fix): Catch 404s in e2e test

---

package-lock.json
package.json
src/components/home/__snapshots__/Home.test.js.snap

Older versions of enzyme-to-json would output explicitly undefined
prop values as `style={undefined}`. Since v3.2.1 it has ommitted
undefind prop values. Our package.json allowed for people to use
either version, and we only just got a package-lock file so PRs
kept failing as we're all using different versions and having to
push changes to snapshots that either fail locally or in ci.
This PR pins enzyme-to-json to the latest for all of us. No more
undefined property values in snapshots. Now we just need to write
some good tests.
Fixes #163
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

chore: fix undefined values in jest snapshots

---

config/webpack.config.prod.js
package-lock.json
package.json
src/components/home/__snapshots__/Home.test.js.snap

- Upgrade the uglifyjs-webpack-plugin to the latest.
- Update prod webpack conf with uglify settings to preserve names.
There is a weird issue that means the running the same
minification steps via a yarn installed dep tree vs an npm one
gives different results. This PR adds ensures that we get some
useful compression on our bundles but ensure that we dont break
IPFS while doing so.
The build now works on npm and yarn, which is nice, and local
testing suggest the IPFS boot time is much faster, which is ✨
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

chore: enable uglify compression

---

config/webpack.config.dev.js
config/webpack.config.prod.js
package-lock.json
package.json
src/components/home/Home.css
src/components/home/Home.js
src/components/home/Home.module.css
src/components/home/__snapshots__/Home.test.js.snap

Ref #169.
This adds configuration for webpack and jest so CSS files ending in `.modules.css` are treated as CSS modules. This allows for CSS files to be optionally refactored over time to convert them from global to local, while also keeping the ability for global CSS files to exist where that makes sense.
It also includes one refactor of the top nav on the homepage to a CSS module as an example of how it works.
One question I wanted to pose is whether it now makes sense to convert all the CSS files (except `colors.css` and `index.css`) to CSS modules, or to do it as time permits going forward.

feat: add css modules

---

config/createStyleRule.js
config/webpack.config.dev.js
config/webpack.config.prod.js
package-lock.json
package.json

This also refactors the style loader implementations into a single config file
that is used for both css and stylus files and across the dev and prod webpack
configurations.
Note that this doesn't add any stylus files. Those will most likely get added as necessary when refactoring as part of #169.
Closes #168

Add stylus as a webpack loader for .styl files

---

ci/Jenkinsfile

This should give us access to a staging and production environment so we can better control what's in production, giving us more flexibility with development and quality assurance.
Per, https://github.com/ipfs-shipyard/peer-pad/issues/152#issuecomment-387812824,
this will give us access to two environments:
| Branch | Environment | URL |
| ------------- |:-------------:| -----:|
| master | staging | https://dev.peerpad.net |
| production | prod | https://peerpad.net |

feat: add a staging server, #152

---

src/components/Edit.js

Resolves https://github.com/ipfs-shipyard/peer-pad/issues/197
This also fixes an issue where joining an existing peer-pad could prevent editing.

fix: editor should no longer break when changing viewmode

---

src/lib/bind-editor.js

The pos pointer wasn't being advanced when adding new characters,
causing subsequent parts of the diff to be applied incorrectly.
This was causing an infinite divergence as other peers amplified
the incorrect diff.

Fix for applying diffs against codemirror

---

package-lock.json
package.json
src/index.js

Adds reporting of errors when they happen on peerpad.net. We should
figure out if we want this to be opt-in or opt-out. Currently it's
neither and always enabled if peerpad is loaded via `peerpad.net`.
Relevant people have received an invitation to the rollbar project as
well.
License: MIT

feat: add error reporting via rollbar

---

README.md
package.json

I don't believe this still holds true or that is wise to distract @jacobheun from his libp2p work (which powers Peer Pad).
Now that there is a Peer Pad team, namely @jimpick @pgte and @parkan, can we have someone new to assume the role of Lead Maintainer?

Lead Maintainer

---

Makefile
package-lock.json
package.json

- npm-run-all depended on a version of flatmap-stream that went 404,
this commit upgrades npm-run-all to a version with no more 404s
- npm@6.0.0 had issues with `write after end` happening from time to
time. This commit upgrades to latest npm, being `6.4.1` at the time of
writing
License: MIT

chore: update npm in Makefile + update npm-run-all

---

package-lock.json
package.json
src/lib/bind-editor.js

Editor locking was presupposed on the `state changed` event emitted by the collaboration being synchronous to changes. Since peer-star-app v0.10.4 that's no longer the case.
Using the `state changed` event emitted by `collaboration.shared` instead.

Fix editor bindings lock

---

src/components/Edit.js
src/components/Editor.js

Reduces the amount of react re-rendering.
Here are some videos to show the impact:
Before: https://gateway.ipfs.io/ipfs/QmV5UdKMTUbmVuz3nLrUSHLidroy8DaBZWZZ5EuB1wUZfH/react-before.mp4
After:
https://gateway.ipfs.io/ipfs/QmQJddeAsL2u8f3pUFwBTVoPTD82CvHwP3LvuB5YiiDEE7/react-after.mp4

Set shouldComponentUpdate to false for codemirror binding

---

src/config.js

This commit basically changes the config depending on if we're in
development or production (`npm start` vs `npm build`), basically so we
don't have to manually change `src/config.js` every time and then
reset before/avoid to commit.
Affected values are the swarm address + bootstraps
License: MIT

chore: better config when in dev vs prod

---

bin/peerpad-print-dump
package-lock.json
package.json
src/lib/bind-editor.js
src/lib/debug-dumper.js

(and tool to print contents)
To dump, in devtools console:
peerPadDevTools.dumpState()
To print dump:
echo '<base64 dump>' | peerpad-print-dump
I made this so I could capture the state for #267. I'm going to merge it right away so I can grab some dumps.

Add quick utility to dump CRDT state to base64 string

---

README.md

Did you want this to point to PeerPad's Contribute.md or IPFS'?

Fixing broken Contributing image link

---

src/components/Edit.js
src/config.js

process.env.APP_NAME and process.env.WEBSOCKET_STAR are overridden
in webpack (probably a bad pattern), so provide some alternatives
for when we provision on Heroku.

Add APP_NAME_(DEV|PROD) and WEBSOCKET_STAR_(DEV|PROD)
